#!/bin/sh
echo "Starting tests..."
python tests.py
if [ $? = 0 ]
then
    echo "Testing succesfull. Commiting changes..."
    exit 0
else
    echo "Failed! Fix your code and run tests before commit."
    exit 1
fi